name: 'action-linear-release-issue'
description: 'Create Linear issue for GitHub release'
author: 'Aleksei Tabakman'
inputs:
  linear-api-key:
    description: 'Linear API key'
    required: true
  linear-team-id:
    description: 'Linear team ID'
    required: true
  linear-issue-title:
    description: 'Linear issue title'
    required: true
  linear-workspace:
    description: 'Linear workspace'
    required: true
  linear-template-id:
    description: 'Linear template ID'
  linear-issue-body:
    description: 'Linear issue body'
  linear-label-release-group:
    description: 'Linear release group'
  linear-label-release-tag:
    description: 'Release tag'
  linear-attachment-url:
    description: 'Linear attachment URL'
outputs:
  linear-release-issue-url:
    description: 'The URL of created Linear issue'
  linear-release-issue-identifier:
    description: 'The identifier of created Linear issue'
  linear-release-issue-title:
    description: 'The title of created Linear issue'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'link'
  color: 'blue'
