const {
  LINEAR_API_KEY,
  LINEAR_TEAM_ID = '',
  LINEAR_TEMPLATE_ID,
  LINEAR_ISSUE_TITLE,
  LINEAR_ISSUE_BODY = '',
  LINEAR_WORKSPACE,
  LINEAR_ATTACHMENT_URL,
} = process.env;

const LINEAR_ISSUE_REGEX = /([A-Z]{2,10}-[0-9]{4,6})/g;

export {
  LINEAR_API_KEY,
  LINEAR_TEAM_ID,
  LINEAR_TEMPLATE_ID,
  LINEAR_ISSUE_TITLE,
  LINEAR_ISSUE_BODY,
  LINEAR_WORKSPACE,
  LINEAR_ATTACHMENT_URL,
  LINEAR_ISSUE_REGEX,
};
